export const FETCH_FILTER_GENRES_REQUEST = 'filter/FETCH_FILTER_GENRES_REQUEST';
export const FETCH_FILTER_GENRES_FAILURE = 'filter/FETCH_FILTER_GENRES_FAILURE';
export const FETCH_FILTER_GENRES_SUCCESS = 'filter/FETCH_FILTER_GENRES_SUCCESS';

export const FETCH_FILTER_SEARCH_REQUEST = 'search/FETCH_FILTER_SEARCH_REQUEST';
export const FETCH_FILTER_SEARCH_FAILURE = 'search/FETCH_FILTER_SEARCH_FAILURE';
export const FETCH_FILTER_SEARCH_SUCCESS = 'search/FETCH_FILTER_SEARCH_SUCCESS';

export const FETCH_SEARCH_REQUEST = 'search/FETCH_SEARCH_REQUEST';
export const FETCH_SEARCH_FAILURE = 'search/FETCH_SEARCH_FAILURE';
export const FETCH_SEARCH_SUCCESS = 'search/FETCH_SEARCH_SUCCESS';
export const SET_PAGE = 'search/SET_PAGE';
export const DO_SEARCH = 'search/DO_SEARCH';
export const SET_FILTER_PARAMS = 'search/SET_FILTER_PARAMS';
export const SET_SEARCH_QUERY = 'search/SET_SEARCH_QUERY';

export const FETCH_SIDEBAR_REQUEST = 'sidebar/FETCH_SIDEBAR_REQUEST';
export const FETCH_SIDEBAR_FAILURE = 'sidebar/FETCH_SIDEBAR_FAILURE';
export const FETCH_SIDEBAR_SUCCESS = 'sidebar/FETCH_SIDEBAR_SUCCESS';
